// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.172
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TaskOutputListener
{
    static class Vsix
    {
        public const string Id = "37225c91-f1f2-478c-a18e-18971404bbba";
        public const string Name = "Task Output Listener";
        public const string Description = "Parses output from Task Runner Explorer to populate the Error List with any errors produced by any task";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "task, error, gulp, grunt, webpack, npm";
    }
}
