// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.172
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TaskOutputListener
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTaskOuputPackageString = "eaf3e2fe-8065-4e8e-9d49-6088af69e5a1";
        public const string TaskOutputCmdSetString = "5beb2bbb-e10c-4407-88a2-92bb0fb597c3";
        public static Guid guidTaskOuputPackage = new Guid(guidTaskOuputPackageString);
        public static Guid TaskOutputCmdSet = new Guid(TaskOutputCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ClearErrorList = 0x0100;
    }
}
